### ISSUE TITLE
Crash below Android 8.0 Oreo

### ISSUE THREAD

**Issue by cwbsl** [osiegmar/FastCSV#16]
When running the example on a device below Android 8.0 Oreo, this LogCat log is created after the crash:

06-14 08:57:12.906 21834-24375/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
    Process: com.app.my, PID: 21834
    java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
        at de.siegmar.fastcsv.writer.CsvWriter.append(CsvWriter.java:149)
        at com.app.my.utils.AirDataUtils.writePath(MyUtils.java:29)
        at com.app.my.activities.MainActivity$56$1$1.run(MainActivity.java:2860)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

After updating the device to Android 8.0 Oreo, it works fine.
My build config:

compileSdkVersion 27
buildToolsVersion '27.0.3'
minSdkVersion 19
targetSdkVersion 27

**Comment by osiegmar** [comment]
Duplicates #3
